### ISSUE TITLE
Issues with making proposals

### ISSUE THREAD

**Issue by qobilidop** [p4lang/p4analyzer#18]
It's mentioned in [Contributing to P4 Analyzer](https://github.com/p4lang/p4analyzer/blob/main/docs/contributing.md) that:
> When creating a proposal, please ensure to add the 'C-proposal' label to it so that we can triage and track it on the [Proposal GitHub Project](https://github.com/orgs/p4lang/projects/1/views/1).

Two issues here:
- I can't edit labels right now. I guess it's a permission issue.
- The link is a 404 to me. I guess it's another permission issue.

**Comment by timjroberts** [comment]
This appears to be a feature of GitHub. We've now created a new 'Proposal' issue template that you can use instead. This will automatically apply the `'C-proposal'` label.

The Project Board is also private by default. I've updated the wording in the linked docs page to better reflect this.
